### ISSUE TITLE
Requirement of college webmail for following new HR Member

### ISSUE THREAD

**Issue by Jenbati** [KhwopaMIS/KhCE#24]
Civil Engineering Department
Er. Anusha Danegulu
Er. Suraj Shah
Er. Prashant Lakhemaru

Electrical Engineering Department
Er. Dhurba Karki

![123](https://user-images.githubusercontent.com/36839891/40532988-fed9ae40-6020-11e8-9c1a-ac3aa303af73.png)

![dhur](https://user-images.githubusercontent.com/36839891/40532998-04e57a26-6021-11e8-96f4-0a92c8e6fc50.png)

**Comment by ErSKS** [comment]
Four accounts created ! Check your email for a/c credentials ...
